import type { Metadata } from "next";
import { Exo_2, Poppins } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { Toaster } from "sonner";
import "@/styles/globals.css";

const poppins = Poppins({
   variable: "--font-poppins",
   weight: ["400", "500", "600", "700"],
   subsets: ["latin"],
});

const exo2 = Exo_2({
   variable: "--font-exo2",
   weight: ["400", "500", "600", "700"],
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Eventra",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${poppins.className} ${exo2.variable} antialiased`}>
            {children}
            <Toaster position="top-center" />
            <Analytics />
         </body>
      </html>
   );
}
